{% set name = "mpi4jax" %}
{% set version = "0.2.16" %}
{% set mpi = mpi or 'mpich' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 54074e29f558e981d0a6260564b92a10bf3c0dc99f4332e5c26eba16fdb70996

build:
  number: 1
  skip: true  # [win or py<37]
  script:
    - {{ PYTHON }} -m pip install --no-deps --ignore-installed --no-cache-dir -vvv .


requirements:
  build:
    - {{ compiler('c') }}
    - setuptools >=45
    - toml
  host:
    - python
    - pip
    - {{ mpi }}
    - mpi4py >=3.0.1
    - cython >=0.21
  run:
    - python
    - numpy
    - jax >=0.2
    - jaxlib
    - {{ mpi }}
    - mpi4py >=3.0.1

test:
  requires:
    - pytest
    - {{ mpi }}
    - openssh  # [linux]
    - tqdm
  imports:
    - mpi4jax

about:
  home: https://github.com/PhilipVinc/mpi4jax
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: MPI support for jax
  description: |
    mpi4jax permits to insert MPI operations inside of jit-compiled jax 
    functions, and to perform automatic differentiation through them.
  doc_url: https://mpi4jax.readthedocs.io
  dev_url: https://github.com/PhilipVinc/mpi4jax

extra:
  recipe-maintainers:
    - PhilipVinc
    - dionhaefner
